// format for importing auto-generated prismaclient...
// Run "npx prisma generate" command to make prisma know about the model name and to create client...

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient()
